import apiConfig from "../apiConfig";

export interface Destination {
  id: number;
  name: string;
  description?: string;
  image_url?: string;
  country: string;
  region: string;
  published: "1" | "0";
}


export const getDestinations = async (): Promise<Destination[]> => {
  const response = await fetch(`${apiConfig.baseurl}destinations/`);
  if (!response.ok) {
    throw new Error("Failed to fetch destinations");
  }
  return response.json();
};

export const getDestinationsWithPagination = async (page: number = 1, limit: number = 10): Promise<{
  destinations: Destination[];
  pagination: {
    page: number;
    limit: number;
    totalPages: number;
    totalRecords: number;
  };
}> => {
  const response = await fetch(`${apiConfig.baseurl}destinations/paginated/?page=${page}&limit=${limit}`);
  if (!response.ok) {
    throw new Error('Failed to fetch destinations with pagination');
  }
  const data = await response.json();
  return {
    destinations: data.destinations,
    pagination: data.pagination,
  };
}

// Adds a new Destination to the API
export const addDestination = async (
  Destination: Omit<Destination, 'id'> // Excludes 'id' since it's generated by the server
): Promise<Destination> => {
  const formData = new FormData();

  // Append the image URL if provided
  if (Destination.image_url) {
    formData.append('image', Destination.image_url);
  }

  // Append other fields to the form data
  Object.entries(Destination).forEach(([key, value]) => {
    if (key !== 'image_url' && value !== undefined && value !== null) {
      formData.append(key, value as string | Blob);
    }
  });

  const response = await fetch(`${apiConfig.baseurl}destinations/`, {
    method: 'POST',
    body: formData,
    headers:apiConfig.headers,
  });

  if (!response.ok) {
    throw new Error('Failed to add Destination');
  }

  return response.json();
};

// Updates an existing Destination in the API
export const updateDestination = async (
  id: number, // ID of the Destination to update
  Destination: Partial<Destination> // Partial object to allow updating specific fields
): Promise<Destination> => {
  const formData = new FormData();

  // Append the image URL if provided
  if (Destination.image_url) {
    formData.append('image', Destination.image_url);
  }

  // Append other fields to the form data
  Object.entries(Destination).forEach(([key, value]) => {
    if (key !== 'image_url' && value !== undefined && value !== null) {
      formData.append(key, value as string | Blob);
    }
  });

  const response = await fetch(`${apiConfig.baseurl}destinations/${id}`, {
    method: 'PUT',
    body: formData,
    headers:apiConfig.headers,
  });

  if (!response.ok) {
    throw new Error('Failed to update Destination');
  }

  return response.json();
};

// Deletes an Destination from the API
export const deleteDestination = async (id: number): Promise<void> => {
  const response = await fetch(`${apiConfig.baseurl}destinations/${id}`, {
    method: 'DELETE',
    headers:apiConfig.headers,
  });

  if (!response.ok) {
    throw new Error('Failed to delete Destination');
  }
};